---
# *** Main configuration file for the SMART-on-FHIR Installer ***

# To customize the SMART-on-FHIR stack, you can either edit the settings directly in
# this file or set up custom settings overrides (such as custom_settings.yml)




#weird shit is going on, here we go











installer_user: "ubuntu"
hosting_userpass: ""

services_host: "localhost"
use_secure_http: false
use_custom_ssl_certificates: false
custom_ssl_certificates_path:
certificate_crt_filename:
certificate_key_filename:
keystore_password: "changeme"

hspc_platform_jwt_key: "changeme"

aws_output_format: 'json'
aws_region: "changeme"
aws_access_key_id: "changeme"
aws_secret_access_key: "changeme"
aws_ec2_volume_id: "changeme"

enable_backup_restore_jobs: false
enable_aws_snapshot: false
enable_pwm: false

mysql_root_pass: "password"
mysql_password: "password"

# apacheds
apacheds_server_external_host: "{{services_host}}"
apacheds_server_system_admin_password: "secret"
apacheds_server_sandbox_admin_password: "password"
# in prod, only install one time
apacheds_server_installer_enabled: true

# pwm
pwm_server_external_host: "{{services_host}}"
pwm_server_external_port: "9092"
pwm_unlocked: true
pwm_configpasswordhash: "changeme"
pwm_securitykey_encrypted: "changeme"
pwm_db_password_encrypted: "changeme"
pwm_sso_authentication_header_name: "changeme"
pwm_ldap_proxy_password_encrypted: "changeme"

auth_server_external_host: "{{services_host}}"
auth_server_external_port: "9060"
auth_server_initial_memory: "32M"
auth_server_max_memory: "128M"
auth_server_newUserUrl: "{{pwm_server_external_url}}public/newuser"
auth_server_forgotPasswordUrl: "{{pwm_server_external_url}}public/forgottenpassword"
auth_server_admin_password: "changeme"
auth_mysql_reset_database: true

api_server_oauth2_clientId: "hspc_resource_server"
api_server_oauth2_clientSecret: "secret"
enable_api_sample_data: true
enable_mock_endpoints: false

api_dstu2_server_external_host: "{{services_host}}"
api_dstu2_server_external_port: "9071"
api_dstu2_server_initial_memory: "128M"
api_dstu2_server_max_memory: "256M"
api_dstu2_mysql_reset_database: true
api_dstu2_sample_patients_limit: "20"

mock_api_dstu2_server_external_host: "{{services_host}}"
mock_api_dstu2_server_external_port: "9271"
mock_api_dstu2_server_initial_memory: "128M"
mock_api_dstu2_server_max_memory: "256M"

api_stu3_server_external_host: "{{services_host}}"
api_stu3_server_external_port: "9074"
api_stu3_server_initial_memory: "128M"
api_stu3_server_max_memory: "256M"
api_stu3_mysql_reset_database: true

mock_api_stu3_server_external_host: "{{services_host}}"
mock_api_stu3_server_external_port: "9274"
mock_api_stu3_server_initial_memory: "128M"
mock_api_stu3_server_max_memory: "256M"

messaging_server_external_host: "localhost"
messaging_server_external_port: "8091"
messaging_server_initial_memory: "1M"
messaging_server_max_memory: "32M"
messaging_profiles: "production"

sandman_server_external_host: "{{services_host}}"
sandman_server_external_port: "9080"
sandman_server_initial_memory: "16M"
sandman_server_max_memory: "128M"
sandman_server_send_email: true
sandbox_server_admin_access_client_secret: "changeme"
sandman_mysql_reset_database: true

apps_server_external_host: "{{services_host}}"
apps_server_external_port: "9093"

patient_picker_server_external_host: "{{apps_server_external_host}}"
patient_picker_server_external_port: "{{apps_server_external_port}}"











#it is the end of the weird shit

installer_user_home: "/home/{{installer_user}}"

#nginx_build_home: "/usr/local"
#nginx_home: "{{nginx_build_home}}/nginx"
nginx_home: "/etc/nginx"

# The user account that will host the servers. If a user account of this name
# already exists on the system, the installer will not alter its credentials or
# authentication mechanism. If you need to set up actual password authentication,
# userpass needs to be a valid SHA-512 hash.
hosting_username: "fhir"
hosting_user_home: "/home/{{hosting_username}}"
hosting_user_aws_config_home: "{{hosting_user_home}}/.aws"
hosting_user_jobs_home: "{{hosting_user_home}}/jobs"
hosting_user_jobs_output_home: "{{hosting_user_jobs_home}}/output"
hosting_user_scripts_home: "{{hosting_user_home}}/scripts"

# Settigs for Jetty and Oracle Java. You probably won't have to alter these
# unles you are switching to a different version of Jetty or Java
java_home: "/usr/lib/jvm/java-8-openjdk-amd64/jre"

top_level_domain: "org"
second_level_domain: "smarthealthit"
additional_subdomains: ""
domain_name: "{{second_level_domain}}.{{top_level_domain}}"
full_domain_name: "{{additional_subdomains}}{{domain_name}}"

# Artifact Repositories
m2_repo_folder: "{{hosting_user_home}}/.m2/repository"
snapshot_repository_url: "https://oss.sonatype.org/content/repositories/snapshots"
release_repository_url: "https://repo1.maven.org/maven2/"
smart_repo_base: "https://github.com/smart-on-fhir"
hspc_repo_base: "https://bitbucket.org/hspconsortium"
# By default Ansible will update the local copies of the servers code from
# the source repositories. Set this to "no" if you would rather not have the
# repositories updated on each run.
update_repositories: "yes"

# jetty_runner Artifact
jetty_runner_artifact_group_id: "org.eclipse.jetty"
jetty_runner_artifact_artifact_id: "jetty-runner"
jetty_runner_artifact_version: "9.3.6.v20151106"
jetty_runner_artifact_packaging: "jar"
jetty_runner_artifact_repository_url: "{{release_repository_url}}"
jetty_runner_artifact_location: "{{m2_repo_folder}}/org/hspconsortium/reference/{{api_server_artifact_artifact_id}}/{{api_server_artifact_version}}/{{api_server_artifact_artifact_id}}-{{api_server_artifact_version}}.{{api_server_artifact_packaging}}"

# Controls whether HTTP requests on port 80 will be
# redirected to the server's base URLs
http_redirect: true

# Maximum size of sample patient data files
max_upload_size: "5M"

# When setting up SSL security for the various services, these settings will allow you to
# specify your own certificates instead of using self-signed certificates.
# See files/sample-certificates for the names of the certificate files expected by the script
use_custom_ssl_certificates: false

# Self-signed SSL certificates settings (if generating self-signed certificates)
self_signed_certificate_ssl_country: "US"
self_signed_certificate_ssl_province: "MA"
self_signed_certificate_ssl_locality: "Boston"
self_signed_certificate_ssl_organization: "Harvard Medical School"
self_signed_certificate_ssl_division: "Dept. of Biomedical Informatics"
self_signed_certificate_ssl_email: ""

# database configuration
mysql_username: "fhir"
mysql_host: "localhost"
mysql_port: 3306
mysql_privilage: "*.*:ALL,GRANT"
mysql_connect_host: "%"

#custom_ssl_certificates_path: examples/certificates
certificate_truststore_alias: "smart"
